apiVersion: apps/v1
kind: Deployment
metadata:
  name: hf-llm-api
  namespace: hf-llm
  labels:
    app: hf-llm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hf-llm-api
  template:
    metadata:
      labels:
        app: hf-llm-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: hf-llm-sa
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: hf-llm-api
          image: hf-llm-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: MODEL_NAME
              value: "distilgpt2"
            - name: MAX_NEW_TOKENS
              value: "80"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: hf-llm-secret
                  key: api-key
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 20
            failureThreshold: 3
          volumeMounts:
            - name: hf-cache
              mountPath: /app/.cache
      volumes:
        - name: hf-cache
          emptyDir: {}
