apiVersion: v1
kind: Service
metadata:
  name: hf-llm-api
  namespace: hf-llm
  labels:
    app: hf-llm-api
spec:
  selector:
    app: hf-llm-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
